name: usp_acessivel
description: "Aplicativo de mapa para tornar o campus da USP mais acessível."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  firebase_core: ^4.13.0
  flutter:
    sdk: flutter
  image_picker: ^1.2.3
  maplibre: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-VariableFont_wght.ttf
  assets:
    - data/
    - assets/tiles/
    - assets/rotas-odonto/
    - assets/map-icons/
