name: meu_campus_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  maplibre: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - data/buildings.json
    - data/ways.json
    - assets/tiles/
    - assets/rotas-odonto/
